---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure Samba-related packages are installed (RedHat).
  package: "name={{ item }} state=present"
  with_items:
    - samba
    - samba-client
    - samba-common
    - cifs-utils
  when: ansible_os_family == 'RedHat'

- name: Ensure Samba-related packages are installed (Debian).
  apt: "name={{ item }} state=present"
  with_items:
    - samba
    - samba-common
    - python-glade2
    - system-config-samba
  when: ansible_os_family == 'Debian'

- name: Ensure Samba is running and set to start on boot.
  service: "name={{ samba_daemon }} state=started enabled=yes"
